name: neo4j
home: https://www.neo4j.com
version: 4.4
appVersion: 4.4.18
description: Neo4j is the world's leading graph database
icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
sources:
  - https://github.com/neo4j/neo4j
  - https://github.com/neo4j/docker-neo4j
  - https://github.com/mneedham/k8s-kubectl
  - https://github.com/neo-technology/neo4j-google-k8s-marketplace
maintainers:
  - name: M. David Allen
    email: david.allen@neo4j.com
  - name: mneedham
    email: mark.needham@neo4j.com
