# Sample pod to be applied manually when desired
# Executes a backup against the DB when tailored to the right endpoint.
# Copies resulting full backup to $BUCKET
apiVersion: v1
kind: Pod
metadata:
  name: neo4j-backup
spec:
  restartPolicy: Never
  containers:
    - name: neo4j-backup
      image: gcr.io/neo4j-k8s-marketplace-public/causal-cluster/backup:4.4
      env:
      - name: NEO4J_ADDR
        value: "neo4j-lsgm-neo4j-core-0.neo4j-lsgm-neo4j.default.svc.cluster.local"
      - name: BUCKET
        value: gs://tmp-k8s-backup-storage
      - name: BACKUP_NAME
        value: my-data
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /auth/credentials.json
      volumeMounts:
      - name: creds
        mountPath: /auth
        readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: neo4j-backup-sa
      items:
      - key: credentials.json
        path: credentials.json
---
apiVersion: v1
kind: Secret
metadata:
  name: "neo4j-backup-sa"
  labels:
    app.kubernetes.io/name: "neo4j-backup-sa"
  annotations:
    marketplace.cloud.google.com/verification: test
data:
  credentials.json: nMIIE